WITH seed_id AS (
  SELECT gen_random_uuid() AS id
)
INSERT INTO users (
  id,
  username,
  password,
  first_name,
  last_name,
  email,
  phone,
  role,
  status,
  avatar_url,
  email_verified,
  booking_url,
  notification_mode,
  notification_sound_enabled,
  notification_sound_type,
  reminder_enabled,
  reminder_mins_before,
  reminder_sound_type,
  last_login_at,
  suspended_reason,
  created_at,
  created_by,
  updated_at,
  updated_by,
  deleted_at,
  deleted_by,
  is_deleted
)
SELECT
  seed_id.id,
  'afaqjaved',
  '$2b$12$oKeoI5cSWasiDKsGarVXAeaSKFMA2N7Kc8mqgsV2h8G9zWEmSyeg2', -- admin12345
  'Afaq',
  'Javed',
  'afaq@afaqjaved.com',
  NULL,
  'Platform Owner',
  'active',
  NULL,
  TRUE,
  'platform-owner',
  'all',
  TRUE,
  'chime',
  TRUE,
  10,
  'chime',
  NULL,
  NULL,
  NOW(),
  seed_id.id,
  NOW(),
  seed_id.id,
  NULL,
  NULL,
  FALSE
FROM seed_id;
